#include <bits/stdc++.h>
using namespace std;
static const long long MOD=998244353;

struct Res{ long long cnt,sum; };
int H,W;
vector<char> colAlive;

// Exact enumeration of all valid matrices.
// A cell may be 1 iff its entire row-prefix so far is 1
// or its entire column-prefix so far is 1.
Res dfs(int pos, bool rowAlive){
    if(pos==H*W) return {1,0};
    int i=pos/W, j=pos%W;
    if(j==0) rowAlive=true;

    bool ca=colAlive[j];
    Res ans{0,0};

    // choose 0
    colAlive[j]=0;
    Res z=dfs(pos+1,false);
    ans.cnt=(ans.cnt+z.cnt)%MOD;
    ans.sum=(ans.sum+z.sum)%MOD;
    colAlive[j]=ca;

    // choose 1 only when it can be generated by a row prefix or a column prefix
    if(rowAlive || ca){
        Res o=dfs(pos+1,rowAlive);
        ans.cnt=(ans.cnt+o.cnt)%MOD;
        ans.sum=(ans.sum+o.sum+o.cnt)%MOD;
    }
    return ans;
}

int main(){
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cin>>H>>W;
    colAlive.assign(W,1);
    cout<<dfs(0,true).sum%MOD<<"\n";
}
